services:
  routemerger.blazor:
    image: routemergerblazor
    container_name: routemerger.blazor
    build:
      context: .
      dockerfile: RouteMerger.Blazor/Dockerfile
    ports:
        - "5000:5000"
    environment:
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
  routemerger.postgres:
    image: postgres:latest
    container_name: routemerger.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: routemergerdb
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  routemerger.seq:
    image: datalust/seq:latest
    container_name: routemerger.seq
    ports:
      - "5341:5341"
      - "8081:80"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seqdata:/var/lib/seq/data

volumes:
    pgdata:
    seqdata: